# From https://github.com/nodejs/docker-node#how-to-use-this-image
version: "3.7"
services:
  # change 'node' to a descriptive name for this service
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    # pulls in this folder and any node_modules, package.json
    volumes:
      - ./:/home/node/app
    expose:
      - "5000"
    ports: 
      - "5000:5000"
    command: "npm start"